// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFiLcRXuyQIbtcLZtWImSSjEgREgOc8EQ',
    appId: '1:271120179295:web:476500447fdc26b1fd3bea',
    messagingSenderId: '271120179295',
    projectId: 'mobideliv',
    authDomain: 'mobideliv.firebaseapp.com',
    storageBucket: 'mobideliv.appspot.com',
    measurementId: 'G-R3P1XY95YE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDL64B0f_PeI4Q7zP8i8VSLMRRE8G6tM4',
    appId: '1:271120179295:android:47fe4ae43c37b8e3fd3bea',
    messagingSenderId: '271120179295',
    projectId: 'mobideliv',
    storageBucket: 'mobideliv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw7A9GgqiR7m3QOySA8-Ae30DBhPeVRcE',
    appId: '1:271120179295:ios:d5268ea6b130e3d0fd3bea',
    messagingSenderId: '271120179295',
    projectId: 'mobideliv',
    storageBucket: 'mobideliv.appspot.com',
    iosClientId: '271120179295-au8tvna5ctjf9ubctoc1hdtho1lt9eb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobideliv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw7A9GgqiR7m3QOySA8-Ae30DBhPeVRcE',
    appId: '1:271120179295:ios:d5268ea6b130e3d0fd3bea',
    messagingSenderId: '271120179295',
    projectId: 'mobideliv',
    storageBucket: 'mobideliv.appspot.com',
    iosClientId: '271120179295-au8tvna5ctjf9ubctoc1hdtho1lt9eb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobideliv',
  );
}
